# Generated by Django 4.0.1 on 2022-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysedStocksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=20, null=True)),
                ('Duration', models.IntegerField(null=True)),
                ('rise2', models.FloatField(null=True)),
                ('rise3', models.FloatField(null=True)),
                ('rise4', models.FloatField(null=True)),
                ('rise5', models.FloatField(null=True)),
                ('rise6', models.FloatField(null=True)),
                ('Jump5', models.FloatField(null=True)),
                ('Jump8', models.FloatField(null=True)),
                ('Jump10', models.FloatField(null=True)),
                ('Jump12', models.FloatField(null=True)),
                ('Jump15', models.FloatField(null=True)),
                ('Down1', models.FloatField(null=True)),
                ('Down2', models.FloatField(null=True)),
                ('Down3', models.FloatField(null=True)),
                ('Down4', models.FloatField(null=True)),
                ('Down5', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-Symbol',),
            },
        ),
        migrations.CreateModel(
            name='GetStocksAngelOne',
            fields=[
                ('token', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('exch_seg', models.CharField(max_length=10, null=True)),
                ('category', models.CharField(max_length=500, null=True)),
                ('tags', models.CharField(max_length=500, null=True)),
                ('exp', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='GetStocksDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=15, null=True)),
                ('Market', models.CharField(max_length=10, null=True)),
                ('pricebandupper', models.FloatField(null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('marketType', models.CharField(max_length=10, null=True)),
                ('dayHigh', models.FloatField(null=True)),
                ('basePrice', models.FloatField(null=True)),
                ('pricebandlower', models.FloatField(null=True)),
                ('dayLow', models.FloatField(null=True)),
                ('pChange', models.FloatField(null=True)),
                ('averagePrice', models.FloatField(null=True)),
                ('cm_ffm', models.FloatField(null=True)),
                ('high52', models.FloatField(null=True)),
                ('previousClose', models.FloatField(null=True)),
                ('low52', models.FloatField(null=True)),
                ('priceBand', models.CharField(max_length=20, null=True)),
                ('varMargin', models.FloatField(null=True)),
                ('change', models.FloatField(null=True)),
                ('series', models.CharField(max_length=10, null=True)),
                ('faceValue', models.FloatField(null=True)),
                ('closePrice', models.FloatField(null=True)),
                ('open', models.FloatField(null=True)),
                ('isinCode', models.CharField(max_length=20, null=True)),
                ('lastPrice', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-Symbol',),
            },
        ),
        migrations.CreateModel(
            name='GetStocksHistoricData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(null=True)),
                ('Symbol', models.CharField(max_length=50, null=True)),
                ('PrevClose', models.FloatField(null=True)),
                ('Open', models.FloatField(null=True)),
                ('High', models.FloatField(null=True)),
                ('Low', models.FloatField(null=True)),
                ('Last', models.FloatField(null=True)),
                ('Close', models.FloatField(null=True)),
                ('HighLow', models.FloatField(null=True)),
                ('JumpingPercent', models.FloatField(null=True)),
                ('PreClose_Close_Change', models.FloatField(null=True)),
                ('RisePercent', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-Symbol',),
            },
        ),
        migrations.CreateModel(
            name='GetStocksList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=15, null=True)),
                ('Market', models.CharField(max_length=10, null=True)),
            ],
            options={
                'ordering': ('-Symbol',),
            },
        ),
    ]
