# Generated by Django 4.0.1 on 2022-01-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedstocksdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='getstocksdailydata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='getstockshistoricdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='getstockslist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
