# Generated by Django 4.0.1 on 2022-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0002_analysedstocksdata_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstockshistoricdata',
            name='token',
            field=models.IntegerField(null=True),
        ),
    ]
