# Generated by Django 4.0.1 on 2022-01-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0003_getstockshistoricdata_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getstocksdailydata',
            options={'ordering': ('-symbol',)},
        ),
        migrations.RenameField(
            model_name='getstocksdailydata',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
