# Generated by Django 4.0.1 on 2022-01-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0004_alter_getstocksdailydata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getstocksdailydata',
            name='isinCode',
        ),
        migrations.RemoveField(
            model_name='getstocksdailydata',
            name='varMargin',
        ),
    ]
