# Generated by Django 4.0.1 on 2022-01-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0006_alter_analysedstocksdata_down1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getstockshistoricdata',
            name='SymName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
