# Generated by Django 4.0.1 on 2022-01-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0007_getstockshistoricdata_symname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getstockshistoricdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
