# Generated by Django 4.0.1 on 2022-01-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0008_alter_getstockshistoricdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetStocksHistoricData',
        ),
    ]
