# Generated by Django 4.0.1 on 2022-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0009_delete_getstockshistoricdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStocksHistoricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(null=True)),
                ('Date', models.DateField(null=True)),
                ('SymName', models.CharField(max_length=50, null=True)),
                ('Symbol', models.CharField(max_length=50, null=True)),
                ('PrevClose', models.FloatField(null=True)),
                ('Open', models.FloatField(null=True)),
                ('High', models.FloatField(null=True)),
                ('Low', models.FloatField(null=True)),
                ('Last', models.FloatField(null=True)),
                ('Close', models.FloatField(null=True)),
                ('HighLow', models.FloatField(null=True)),
                ('JumpingPercent', models.FloatField(null=True)),
                ('PreClose_Close_Change', models.FloatField(null=True)),
                ('RisePercent', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-Symbol',),
            },
        ),
    ]
