# Generated by Django 4.0.1 on 2022-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nse', '0010_getstockshistoricdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoResultFoundStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(null=True)),
                ('symbol', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('-symbol',),
            },
        ),
    ]
